### PR TITLE
Add Italian Translation

### PR DESCRIPTION
**Pull request by albanobattistella**

### CODE REVIEW

**Comment by wiiznokes** [comment]
Thanks!

**Comment by wiiznokes** [comment]
Your files should be in a new `it` directory, like `fr` and `en`. The abreviation follow this iso: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes

**Comment by albanobattistella** [comment]
> Your files should be in a new `it` directory, like `fr` and `en`. The abreviation follow this iso: https://en.wikipedia.org/wiki/List_of_ISO_639_language_codes

Hi,
I tried to do a directory but I can't.

**Review by wiiznokes — CHANGES_REQUESTED** [review]

**Comment by wiiznokes** [comment]
> Hi,
I tried to do a directory but I can't.

Weird, i will do it then, no problem

**Comment by wiiznokes** [comment]
@albanobattistella I can't push commit on your pull request, please check the box "Allow edits from maintainers" in this page if it's possible

```
error: Authentication error: Authentication required: You must have push access to verify locks
error: failed to push some refs to 'https://github.com/albanobattistella/fan-control.git'
```

**Pull request closed without merging**
